services:
  hive-metastore:
    image: docker.io/apache/hive:4.0.0
    container_name: rat-hive-metastore
    ports:
      - "9083:9083"
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: derby
    volumes:
      - hive-metastore-data:/opt/hive/data

volumes:
  hive-metastore-data:
